<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.appbundle_command_rsscommand' shared autowired service.

require_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Command\\Command.php';
require_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Command\\ContainerAwareCommand.php';
require_once $this->targetDirs[3].'\\src\\AppBundle\\Util\\Utils.php';
require_once $this->targetDirs[3].'\\src\\AppBundle\\Command\\RssCommand.php';

return $this->services['console.command.appbundle_command_rsscommand'] = new \AppBundle\Command\RssCommand(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
