<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'GetFeed' shared autowired service.

require_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\FeedServices.php';

return $this->services['GetFeed'] = new \AppBundle\Service\FeedServices(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, $this);
