<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerAfxt0ie\appTestDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerAfxt0ie/appTestDebugProjectContainer.php';
}

if (!class_exists(appTestDebugProjectContainer::class, false)) {
    class_alias(\ContainerAfxt0ie\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerAfxt0ie\appTestDebugProjectContainer();
