<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerNzoan5q\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerNzoan5q/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerNzoan5q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNzoan5q\appDevDebugProjectContainer();
